# Generated by Django 4.2.11 on 2025-11-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='video_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='video_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='video_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
