# Generated by Django 4.2.11 on 2025-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0002_downloadrequest_video_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
