# Generated by Django 4.2.11 on 2025-11-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0003_downloadrequest_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='is_playlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='playlist_count',
            field=models.IntegerField(default=0),
        ),
    ]
