# Generated by Django 4.2.11 on 2025-11-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0004_downloadrequest_is_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='is_playlist',
        ),
        migrations.RemoveField(
            model_name='downloadrequest',
            name='playlist_count',
        ),
    ]
