# Generated by Django 4.2.11 on 2025-11-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0005_remove_downloadrequest_is_playlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='downloadrequest',
            name='session_id',
        ),
    ]
