# Generated by Django 4.2.11 on 2025-11-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0006_remove_downloadrequest_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='downloadrequest',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
