# Generated by Django 4.2.11 on 2025-11-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0007_downloadrequest_device_id_downloadrequest_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadrequest',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
