# Generated by Django 4.2.11 on 2025-11-15 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_mp4', '0008_downloadrequest_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadrequest',
            name='error_message',
        ),
    ]
